server:
  ports: 8090

spring:
  profiles:
    active: dev
    
---
spring:
  profiles: dev
  pid.file: dev_idmanager.pid
  devtools: 
    livereload:
      enabled: true
auth:
  secretKey: "ABCDE"
  
web:
  path:
    error: "123"
    
logging:
  level:
    web: DEBUG
    
---
spring:
  profiles: prod
